AWSTemplateFormatVersion: '2010-09-09'
Description: 'Fashion Check Ranking'

Parameters:
  GlobalPrefix:
    Type: String
    Default: 'fashioncheckranking'
  GlobalEnvironment:
    Type: String
    Default: 'production'
  # LambdaSourceS3KeyCrawler:
  #   Type: String
  #   Default: 'lambda/crawler.zip'

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: 'Retain'
    Properties:
      AccessControl: 'Private'
      BucketName: !Sub ${AWS::StackName}
      Tags:
        - Key: 'Scope'
          Value: !Ref GlobalEnvironment
      VersioningConfiguration:
        Status: 'Enabled'
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: FashionCheckLankingRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: lambda
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: '*'
  # ScheduledRule:
  #   Type: AWS::Events::Rule
  #   Properties:
  #     Description: ScheduledRule
  #     ScheduleExpression: 'cron(0/2 * * * ? *)'
  #     State: ENABLED
  #     Targets:
  #     - Arn: !GetAtt LambdaFunctionCrawler.Arn
  #       Id: TargetFunctionV1
  # PermissionForEventsToInvokeLambda:
  #   Type: AWS::Lambda::Permission
  #   Properties:
  #     FunctionName: !Ref LambdaFunctionCrawler
  #     Action: lambda:InvokeFunction
  #     Principal: events.amazonaws.com
  #     SourceArn: !GetAtt 'ScheduledRule.Arn'
  # LambdaFunctionCrawler:
  #   Type: AWS::Lambda::Function
  #   Properties:
  #     Code:
  #       S3Bucket: !Ref S3Bucket
  #       S3Key: !Ref LambdaSourceS3KeyCrawler
  #     Handler: crawler.handler
  #     Role: !GetAtt LambdaExecutionRole.Arn
  #     Runtime: ruby2.5
  #     MemorySize: 128
  #     Timeout: 30
  #     Environment:
  #       Variables:
  #         'prefix': !Ref GlobalPrefix
  #         'environment': !Ref GlobalEnvironment
  #     Tags:
  #     - Key: Name
  #       Value: !Ref GlobalPrefix
  #     - Key: Environment
  #       Value: !Ref GlobalEnvironment
  #     - Key: CloudformationArn
  #       Value: !Ref 'AWS::StackId'
